services:
  database:
    image: postgres
    container_name: databse
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=money_tracker_dev
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: money_tracker_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
