version: "3.9"

services:
  database:
    image: postgres
    container_name: database_communicash
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=b252fc5b24342d14cf04c1e6810dae5c
      - POSTGRES_DB=money_tracker_dev
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: money_tracker_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
